spring:
  application:
    name: edu-tracker-professor
  datasource:
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: slj-edutracker-rabbit
    port: 5672
    username: root
    password: 1234

server:
  servlet:
    context-path: /edu-tracker/teach/
  host: localhost
  port: 8081

minio:
  accessKey: admin
  secretKey: password
  endpoint: http://minio:9000

sendgrid:
  api:
    key: ${SG_KEY}
    from: ${SG_FROM}